#
# Author: MrCubee
#
world:
  name: world
  loadSize: 320
  terrainFormingSize: 60
  border:
    max: 2000
    min: 1
    time: 2700
player:
  max: 100
  min: 10
game:
  startTime: 60
  restartTime: 20
  step:
    pvpTime: 300
    feast:
      beforeTime: 1200
      spawnTime: 600