name: ${name}
version: ${version}
website: ${url}
description: ${description}
api-version: 1.8
author: MrCubee
main: fr.mrcubee.survivalgames.SurvivalGames
commands:
  forcestart:
    permission: minigame.command.forcestart
  lang: