name: ${name}
version: ${version}
website: ${url}
description: ${description}
api-version: 1.8
author: MrCubee
main: fr.mrcubee.hungergames.HungerGames
commands:
  forcestart:
    permission: minigame.command.forcestart
  kit:
    permission: hg.kit.set
  lang: